/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.23
 * Generated at: 2023-01-12 11:26:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import com.LearnerAcademy.DBConfig.DBConfig;

public final class manageSession_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.LearnerAcademy.DBConfig.DBConfig");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Manage Session</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"dashboard.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body  class=\"bg-light\">\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	");

		String session_u_name = (String)session.getAttribute("usname");
		String role = (String)session.getAttribute("role");	
	
		if(role != "admin"){
			response.sendRedirect("admin.jsp");
			
		}
		
		DBConfig dbc = new DBConfig();
		
		String driverName = dbc.getDriverName();
		String connectionUrl = dbc.getConnectionUrl();
		String dbName = dbc.getDbName();
		String userId = dbc.getUserId();
		String password = dbc.getPassword();
		
		
		String action = (String) request.getParameter("action");
		
		try {
			Class.forName(driverName);
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
	
		Connection connection = null;
		Statement statement = null;
		ResultSet resultSet = null;
		ResultSet teacherRes = null;
		ResultSet subRes = null;
	
		try{
			
			connection = DriverManager.getConnection(connectionUrl+dbName, userId, password);
			statement=connection.createStatement();
		
			//deleting division
			if(action.equals("deleteStudent") && request.getParameter("studentId") != null){
				PreparedStatement delPS = connection.prepareStatement("DELETE FROM student where id=?");
				delPS.setString(1, request.getParameter("studentId"));
				delPS.execute();
			}
		}catch(Exception e){
			e.printStackTrace();
		}
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<main>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebarComp.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"data\">\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "headerComp.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("	\r\n");
      out.write("	<div class=\"p-3 control\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("			<div class=\"col-sm-6\">\r\n");
      out.write("				<h4><i class=\"bi bi-person-video2\"></i> Manage Sessions</h4>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  	<div class=\"my-3 p-3 bg-body rounded shadow-sm\">\r\n");
      out.write("  	\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("  <div class=\"col-lg-6 col-md-6 \">\r\n");
      out.write("  <form id=\"sesDateSel\" action=\"");
      out.print(request.getContextPath());
      out.write("/manageSession.jsp\" method=\"post\"  class=\"row \">\r\n");
      out.write("  	<div class=\"\">\r\n");
      out.write("    <input type=\"hidden\" name=\"action\" value=\"dateSelector\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-6\">\r\n");
      out.write("		<input type=\"date\" class=\"form-control\" name=\"sesDate\" onchange=\"document.getElementById('sesDateSel').submit();\">\r\n");
      out.write("	</div>\r\n");
      out.write("  </form>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"my-3\">\r\n");
      out.write("		");

		
			//out.print("Content: " + action + " for std, " + request.getParameter("selectedStd"));
			if(action != null ){
				
				
				if( action.equals("dateSelector") || action.equals("deleteStudent")){
					
					PreparedStatement ps = connection.prepareStatement("SELECT * FROM session where sessionDate=?");
					ps.setString(1, request.getParameter("sesDate"));
					
					
      out.write("\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("					<div class=\"col-lg-6 col-sm-6\">\r\n");
      out.write("					\r\n");
      out.write("					<h4>Sessions on ");
      out.print( request.getParameter("sesDate") );
      out.write("</h4>\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<hr/>\r\n");
      out.write("					");

					
						
					try{
											
						
						resultSet = ps.executeQuery();
						
						
							
      out.write("\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("						\r\n");
      out.write("								");
 while(resultSet.next()){ 
      out.write("\r\n");
      out.write("							\r\n");
      out.write("								<div class=\"col-lg-4 col-md-6 col-sm-12 px-3 py-1\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\" p-3 bg-body rounded shadow-sm\">\r\n");
      out.write("					<h5>");
      out.print( resultSet.getString("sessionName") );
      out.write("</h5>\r\n");
      out.write("					<p>Time: <span class=\"badge bg-primary\"> ");
      out.print( resultSet.getString("sessionDate") );
      out.write(" at ");
      out.print( resultSet.getString("sessionStartTime") );
      out.write("</span></p>\r\n");
      out.write("					<hr/>\r\n");
      out.write("					<ul class=\"list-group list-group-flush\">\r\n");
      out.write("					<li class=\"list-group-item\">Teacher: ");

					PreparedStatement psTeacher = connection.prepareStatement("SELECT * FROM teacher where id=?");
					psTeacher.setString(1, resultSet.getString("teacher"));
					teacherRes = psTeacher.executeQuery();
					
						while(teacherRes.next()){
							out.print(teacherRes.getString("name"));
						}
					
					
      out.write("</li>\r\n");
      out.write("					<li class=\"list-group-item\">Subject: ");

					PreparedStatement pssub = connection.prepareStatement("SELECT * FROM subject where id=?");
					pssub.setString(1, resultSet.getString("subject"));
					subRes = pssub.executeQuery();
					
						while(subRes.next()){
							out.print(subRes.getString("name"));
						}
					
					
      out.write("</li>\r\n");
      out.write("					<li class=\"list-group-item\">Standard: ");
      out.print( resultSet.getString("std") );
      out.write("</li>\r\n");
      out.write("					<li class=\"list-group-item\">Division: ");
      out.print( resultSet.getString("class") );
      out.write("</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<br/>\r\n");
      out.write("					<form method=\"post\" action=\"viewSessionInfo.jsp\">\r\n");
      out.write("						<input type=\"hidden\" name=\"sesId\" value=\"");
      out.print( resultSet.getString("id") );
      out.write("\">\r\n");
      out.write("						<input class=\"btn btn-primary\" type=\"submit\" value=\"More Info\">\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				</div>\r\n");
      out.write("								\r\n");
      out.write("								");
 } 
      out.write("\r\n");
      out.write("								\r\n");
      out.write("						</div>\r\n");
      out.write("			");

						
					}catch(Exception e){
						e.printStackTrace();
					}
					
			
				}
				
				
			}else{
				
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				<h4 class=\"text-center\">Please select date for which you want to view the sessions.</h4>\r\n");
      out.write("				\r\n");
      out.write("				");

			}
		
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- /main content -->\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
