/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.23
 * Generated at: 2023-01-12 07:24:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;

public final class scheduleSession_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.text.ParseException");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Schedule Session</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"dashboard.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-light\">\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	");

		String session_u_name = (String)session.getAttribute("usname");
		String role = (String)session.getAttribute("role");	
	
		if(role != "admin"){
			response.sendRedirect(request.getContextPath() + "/admin.jsp");
			
		}
		
		String driverName = "com.mysql.jdbc.Driver";
		String connectionUrl = "jdbc:mysql://localhost:3306/";
		String dbName = "learnersacademy";
		String userId = "root";
		String password = "root12345";
		
		String action = (String)request.getParameter("action");

		try {
			Class.forName(driverName);
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
	
		Connection connection = null;
		Statement statement = null;
		ResultSet resultSet = null;
	
		try{
			
			connection = DriverManager.getConnection(connectionUrl+dbName, userId, password);
			statement=connection.createStatement();
		
		}catch(Exception e){
			e.printStackTrace();
		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("<main>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebarComp.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"data\">\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "headerComp.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("	\r\n");
      out.write("	<div class=\"p-3 control\">\r\n");
      out.write("\r\n");
      out.write("	<h3> <i class=\"bi bi-person-video2\"></i> Schedule Session</h3>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	");

	
	String sesName = "";
	String sesDate = "";
	String sesStart = "";
	String sesEnd = "";
	String sesStd = "";
	String sesDiv = "";
	String sesSub = "";
	String sesTeach = "";
	
	if(request.getParameter("action") != null && action.equals("creation")){
		
		if(request.getParameter("status") != null && request.getParameter("status").equals("1")){
			
      out.write("\r\n");
      out.write("			<div class=\"alert alert-success\" role=\"alert\">\r\n");
      out.write("			 Class Created successfully!\r\n");
      out.write("			</div>\r\n");
      out.write("						\r\n");
      out.write("			");

		}else if(request.getParameter("status") != null && request.getParameter("status").equals("0")){
			
      out.write("\r\n");
      out.write("			<div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("			 Unable to create the class, Try again!\r\n");
      out.write("			</div>\r\n");
      out.write("						\r\n");
      out.write("			");

			
		}
		
	}
	
	if(request.getParameter("sesName") != null){
		sesName = request.getParameter("sesName");
	}
	
	if(request.getParameter("sesDate") != null){
		sesDate = request.getParameter("sesDate");
	}
	
	if(request.getParameter("sesStart") != null){
		sesStart = request.getParameter("sesStart");
	}
	
	if(request.getParameter("sesEnd") != null){
		sesEnd = request.getParameter("sesEnd");
	}
	
	if(request.getParameter("sesStd") != null){
		sesStd = request.getParameter("sesStd");
	}
	
	if(request.getParameter("sesDiv") != null){
		sesDiv = request.getParameter("sesDiv");
	}
	
	if(request.getParameter("sesSub") != null){
		sesSub = request.getParameter("sesSub");
	}
	
	if(request.getParameter("sesTeach") != null){
		sesTeach = request.getParameter("sesTeach");
	}
	
	
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"my-3 p-3 bg-body rounded shadow-sm\">\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("		");

		
		if(request.getParameter("step") != null && request.getParameter("step").equals("5")){
			
      out.write("\r\n");
      out.write("			<form method=\"post\" action=\"");
      out.print( request.getContextPath() );
      out.write("/scheduleSession.jsp\">\r\n");
      out.write("					<input type=\"hidden\" disabled name=\"action\" value=\"createSession\">\r\n");
      out.write("					\r\n");
      out.write("					<div class=\" g-3 mb-3 align-items-center\">\r\n");
      out.write("					  <div class=\"col-5\">\r\n");
      out.write("					    <label for=\"sesName\" class=\"col-form-label\">Session Name</label>\r\n");
      out.write("					  </div>\r\n");
      out.write("					  <div class=\"col-auto\">\r\n");
      out.write("						<input  class=\"form-control\"  type=\"text\" disabled name=\"sesName\" value=\"");
      out.print( sesName );
      out.write("\">\r\n");
      out.write("					  </div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\" g-3 mb-3 align-items-center\">\r\n");
      out.write("					  <div class=\"col-5\">\r\n");
      out.write("					    <label for=\"sesDate\" class=\"col-form-label\">Session Date</label>\r\n");
      out.write("					  </div>\r\n");
      out.write("					  <div class=\"col-auto\">\r\n");
      out.write("						<input  class=\"form-control\"  type=\"text\" disabled name=\"sesDate\" value=\"");
      out.print( sesDate );
      out.write("\">\r\n");
      out.write("					  </div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\" g-3 mb-3 align-items-center\">\r\n");
      out.write("					  <div class=\"col-5\">\r\n");
      out.write("					    <label for=\"sesStart\" class=\"col-form-label\">Session Start Time</label>\r\n");
      out.write("					  </div>\r\n");
      out.write("					  <div class=\"col-auto\">\r\n");
      out.write("						<input  class=\"form-control\"  type=\"text\" disabled name=\"sesStart\" value=\"");
      out.print( sesStart );
      out.write("\">\r\n");
      out.write("					  </div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\" g-3 mb-3 align-items-center\">\r\n");
      out.write("					  <div class=\"col-5\">\r\n");
      out.write("					    <label for=\"sesEnd\" class=\"col-form-label\">Session End Time</label>\r\n");
      out.write("					  </div>\r\n");
      out.write("					  <div class=\"col-auto\">\r\n");
      out.write("						<input  class=\"form-control\"  type=\"text\" disabled name=\"sesEnd\" value=\"");
      out.print( sesEnd );
      out.write("\">\r\n");
      out.write("					  </div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<div class=\" g-3 mb-3 align-items-center\">\r\n");
      out.write("					  <div class=\"col-5\">\r\n");
      out.write("					    <label for=\"sesStd\" class=\"col-form-label\">Standard</label>\r\n");
      out.write("					  </div>\r\n");
      out.write("					  <div class=\"col-auto\">\r\n");
      out.write("						<input  class=\"form-control\"  type=\"text\" disabled name=\"sesStd\" value=\"");
      out.print( sesStd );
      out.write("\">\r\n");
      out.write("					  </div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\" g-3 mb-3 align-items-center\">\r\n");
      out.write("					  <div class=\"col-5\">\r\n");
      out.write("					    <label for=\"sesDiv\" class=\"col-form-label\">Division</label>\r\n");
      out.write("					  </div>\r\n");
      out.write("					  <div class=\"col-auto\">\r\n");
      out.write("						<input  class=\"form-control\"  type=\"text\" disabled name=\"sesDiv\" value=\"");
      out.print( sesDiv );
      out.write("\">\r\n");
      out.write("					  </div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\" g-3 mb-3 align-items-center\">\r\n");
      out.write("					  <div class=\"col-5\">\r\n");
      out.write("					    <label for=\"sesSub\" class=\"col-form-label\">Session Subject</label>\r\n");
      out.write("					  </div>\r\n");
      out.write("					  <div class=\"col-auto\">\r\n");
      out.write("						<input  class=\"form-control\"  type=\"text\" disabled name=\"sesSub\" value=\"");
      out.print( sesSub );
      out.write("\">\r\n");
      out.write("					  </div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\" g-3 mb-3 align-items-center\">\r\n");
      out.write("					  <div class=\"col-5\">\r\n");
      out.write("					    <label for=\"sesTeach\" class=\"col-form-label\">Session Teacher</label>\r\n");
      out.write("					  </div>\r\n");
      out.write("					  <div class=\"col-auto\">\r\n");
      out.write("						<input  class=\"form-control\"  type=\"text\" disabled name=\"sesTeach\" value=\"");
      out.print( sesTeach );
      out.write("\">\r\n");
      out.write("					  </div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					<input class=\"btn btn-primary\" type=\"submit\" value=\"Create Session\">\r\n");
      out.write("				</form>\r\n");
      out.write("			");
 
		}
		
		if(request.getParameter("step") != null){
			
			if( !request.getParameter("step").equals("5")){
				
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				<form method=\"post\" action=\"");
      out.print( request.getContextPath() );
      out.write("/scheduleSession.jsp\">\r\n");
      out.write("					<input type=\"hidden\" name=\"action\" value=\"createSession\">\r\n");
      out.write("					<input type=\"hidden\" name=\"sesName\" value=\"");
      out.print( sesName );
      out.write("\">\r\n");
      out.write("					<input type=\"hidden\" name=\"sesDate\" value=\"");
      out.print( sesDate );
      out.write("\">\r\n");
      out.write("					<input type=\"hidden\" name=\"sesStart\" value=\"");
      out.print( sesStart );
      out.write("\">\r\n");
      out.write("					<input type=\"hidden\" name=\"sesEnd\" value=\"");
      out.print( sesEnd );
      out.write("\">\r\n");
      out.write("					\r\n");
      out.write("					");
 if(request.getParameter("step").equals("1")){ 
      out.write("\r\n");
      out.write("					<div class=\" g-3 mb-3 align-items-center\">\r\n");
      out.write("					  <div class=\"col-5\">\r\n");
      out.write("					    <label for=\"sesStd\" class=\"col-form-label\">Standard</label>\r\n");
      out.write("					  </div>\r\n");
      out.write("					  <div class=\"col-auto\">\r\n");
      out.write("					    <select class=\"form-control\"  name=\"sesStd\"  id=\"sesStd\">\r\n");
      out.write("							");

							
								try{
									
									String sql ="SELECT DISTINCT std FROM class";
						
									resultSet = statement.executeQuery(sql);
									
									while(resultSet.next()){
										
      out.write("\r\n");
      out.write("										<option value=\"");
      out.print(resultSet.getString("std") );
      out.write('"');
      out.write(' ');
 if(resultSet.getString("std").equals(request.getParameter("sesStd"))){ 
      out.write(" selected=\"selected\" ");
 } 
      out.write('>');
      out.print(resultSet.getString("std") );
      out.write("</option>\r\n");
      out.write("										");

									}
						
									
								}catch(Exception e){
									e.printStackTrace();
								}
							
							
      out.write("\r\n");
      out.write("							\r\n");
      out.write("							</select>\r\n");
      out.write("					  </div>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<input type=\"hidden\" name=\"step\" value=\"2\">\r\n");
      out.write("					");
 }else{
						
						
      out.write(" \r\n");
      out.write("						\r\n");
      out.write("							<input type=\"hidden\" name=\"sesStd\" value=\"");
      out.print( sesStd );
      out.write("\">\r\n");
      out.write("							\r\n");
      out.write("						\r\n");
      out.write("						");

						
					} //step1
					
					
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					 \r\n");
      out.write("					\r\n");
      out.write("					");

					if(request.getParameter("step").equals("2")){
						
						try{
							
							PreparedStatement divSelPS = connection.prepareStatement("SELECT DISTINCT class FROM class WHERE std=?");
							divSelPS.setString(1, request.getParameter("sesStd"));
				
							resultSet = divSelPS.executeQuery();
							
							if(resultSet.next()) {
								
								
      out.write("\r\n");
      out.write("								\r\n");
      out.write("								<div class=\" g-3 mb-3 align-items-center\">\r\n");
      out.write("						  <div class=\"col-5\">\r\n");
      out.write("						    <label for=\"sesDiv\" class=\"col-form-label\">Session Division</label>\r\n");
      out.write("						  </div>\r\n");
      out.write("						  <div class=\"col-auto\">\r\n");
      out.write("						   <select class=\"form-control\" required  name=\"sesDiv\"  id=\"sesDiv\">\r\n");
      out.write("							");

								do{
									
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									<option value=\"");
      out.print(resultSet.getString("class") );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(resultSet.getString("class") );
      out.write("</option>\r\n");
      out.write("						\r\n");
      out.write("									");

								}while(resultSet.next());
							
							
      out.write("\r\n");
      out.write("							</select>\r\n");
      out.write("						   </div>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("					<input type=\"hidden\" name=\"step\" value=\"3\">\r\n");
      out.write("								");

								
							}
						}catch(Exception e){
							e.printStackTrace();
						}
					
					}else{
						
						
      out.write(" \r\n");
      out.write("						<input type=\"hidden\" name=\"sesDiv\" value=\"");
      out.print( sesDiv );
      out.write("\">\r\n");
      out.write("						\r\n");
      out.write("					\r\n");
      out.write("						");

						
					}//step 2
					
					
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					");

					if(request.getParameter("step").equals("3")){
						
						try{
							
							PreparedStatement subSelPS = connection.prepareStatement("SELECT * from subject WHERE class=?");
							subSelPS.setString(1, request.getParameter("sesStd"));
				
							resultSet = subSelPS.executeQuery();
							
							if(resultSet.next()) {
								
								
      out.write("\r\n");
      out.write("								\r\n");
      out.write("								<div class=\" g-3 mb-3 align-items-center\">\r\n");
      out.write("						  <div class=\"col-5\">\r\n");
      out.write("						    <label for=\"sesSub\" class=\"col-form-label\">Session Subject</label>\r\n");
      out.write("						  </div>\r\n");
      out.write("						  <div class=\"col-auto\">\r\n");
      out.write("						   <select class=\"form-control\" required  name=\"sesSub\"  id=\"sesSub\">\r\n");
      out.write("							");

								do{
									
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									<option value=\"");
      out.print(resultSet.getString("id") );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(resultSet.getString("name") );
      out.write("</option>\r\n");
      out.write("						\r\n");
      out.write("									");

								}while(resultSet.next());
							
							
      out.write("\r\n");
      out.write("							</select>\r\n");
      out.write("						   </div>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("					<input type=\"hidden\" name=\"step\" value=\"4\">\r\n");
      out.write("								");

								
							}
						}catch(Exception e){
							e.printStackTrace();
						}
					
					}else{
						
						
      out.write(" \r\n");
      out.write("						<input type=\"hidden\" name=\"sesSub\" value=\"");
      out.print( sesSub );
      out.write("\">\r\n");
      out.write("						\r\n");
      out.write("					\r\n");
      out.write("						");

						
					}//step 3
					
					
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					");

					if(request.getParameter("step").equals("4")){
						
						try{
							
							PreparedStatement teachSelPS = connection.prepareStatement("SELECT * from teacher");
				
							resultSet = teachSelPS.executeQuery();
							
							if(resultSet.next()) {
								
								
      out.write("\r\n");
      out.write("								\r\n");
      out.write("								<div class=\" g-3 mb-3 align-items-center\">\r\n");
      out.write("						  <div class=\"col-5\">\r\n");
      out.write("						    <label for=\"sesTeach\" class=\"col-form-label\">Session Teacher</label>\r\n");
      out.write("						  </div>\r\n");
      out.write("						  <div class=\"col-auto\">\r\n");
      out.write("						   <select class=\"form-control\" required  name=\"sesTeach\"  id=\"sesTeach\">\r\n");
      out.write("							");

								do{
									
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									<option value=\"");
      out.print(resultSet.getString("id") );
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(resultSet.getString("name") );
      out.write("</option>\r\n");
      out.write("						\r\n");
      out.write("									");

								}while(resultSet.next());
							
							
      out.write("\r\n");
      out.write("							</select>\r\n");
      out.write("						   </div>\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("					<input type=\"hidden\" name=\"step\" value=\"5\">\r\n");
      out.write("								");

								
							}
						}catch(Exception e){
							e.printStackTrace();
						}
					
					}else{
						
						
      out.write(" \r\n");
      out.write("						<input type=\"hidden\" name=\"sesTeach\" value=\"");
      out.print( sesTeach );
      out.write("\">\r\n");
      out.write("						\r\n");
      out.write("					\r\n");
      out.write("						");

						
					}//step 3
					
					
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					<input class=\"btn btn-primary\" type=\"submit\" value=\"Next\">\r\n");
      out.write("					<input class=\"btn btn-light\" type=\"reset\" value=\"Reset\">\r\n");
      out.write("				</form>\r\n");
      out.write("				");

			}
		}else{
		
		
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		<form method=\"post\" action=\"");
      out.print( request.getContextPath() );
      out.write("/scheduleSession.jsp\">\r\n");
      out.write("		\r\n");
      out.write("		<input type=\"hidden\" name=\"action\" value=\"createSession\">\r\n");
      out.write("		<input type=\"hidden\" name=\"step\" value=\"1\">\r\n");
      out.write("		\r\n");
      out.write("		<div class=\" g-3 mb-3 align-items-center\">\r\n");
      out.write("		  <div class=\"col-5\">\r\n");
      out.write("		    <label for=\"sesName\" class=\"col-form-label\">Session Name</label>\r\n");
      out.write("		  </div>\r\n");
      out.write("		  <div class=\"col-auto\">\r\n");
      out.write("		    <input type=\"text\" id=\"sesName\" name=\"sesName\" value=\"");
      out.print( sesName );
      out.write("\" required class=\"form-control\" aria-describedby=\"Session Name\">\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		");

			java.sql.Date dateStr=new java.sql.Date(System.currentTimeMillis());
		    			
		
		
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<div class=\" g-3 mb-3 align-items-center\">\r\n");
      out.write("		  <div class=\"col-5\">\r\n");
      out.write("		    <label for=\"sesDate\" class=\"col-form-label\">Session Date</label>\r\n");
      out.write("		  </div>\r\n");
      out.write("		  <div class=\"col-auto\">\r\n");
      out.write("		    <input type=\"date\" id=\"sesDate\" min=\"");
      out.print( dateStr );
      out.write("\" name=\"sesDate\" value=\"");
      out.print( sesDate );
      out.write("\" required class=\"form-control\" aria-describedby=\"session Date\">\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\" g-3 mb-3 align-items-center\">\r\n");
      out.write("		  <div class=\"col-5\">\r\n");
      out.write("		    <label for=\"sesStart\" class=\"col-form-label\">Session Start Time</label>\r\n");
      out.write("		  </div>\r\n");
      out.write("		  <div class=\"col-auto\">\r\n");
      out.write("		    <input type=\"time\"  onchange=\"updateEndTime()\"  id=\"sesStart\" name=\"sesStart\" value=\"");
      out.print( sesStart );
      out.write("\" required class=\"form-control\" aria-describedby=\"sesStart\">\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\" g-3 mb-3 align-items-center\">\r\n");
      out.write("		  <div class=\"col-5\">\r\n");
      out.write("		    <label for=\"sesEnd\" class=\"col-form-label\">Session End Time</label>\r\n");
      out.write("		  </div>\r\n");
      out.write("		  <div class=\"col-auto\">\r\n");
      out.write("		    <input type=\"time\" id=\"sesEnd\" name=\"sesEnd\" value=\"");
      out.print( sesEnd );
      out.write("\" required class=\"form-control\" aria-describedby=\"sesEnd\">\r\n");
      out.write("		  </div>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<input class=\"btn btn-primary\" type=\"submit\" value=\"Next\">\r\n");
      out.write("		<input class=\"btn btn-light\" type=\"reset\" value=\"Reset\">\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		</form>\r\n");
      out.write("		\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div><!-- white card -->\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- /main content -->\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	</main>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	function updateEndTime(){\r\n");
      out.write("		let st = document.getElementById('sesStart').value;\r\n");
      out.write("		document.getElementById(\"sesEnd\").min = st;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
